=== ChristophDelfs/CCAN_Integration/custom_components/ccan/production/CCAN_schema.json
{
    "$schema": "http://json-schema.org/draft/2019-09/schema",
    "title": "CCAN Production Config",
    "type": "object",
    "required": ["CONFIGURATION_PATH","UDP_SERVER"],
    "properties":
    {
      "UDP_SERVER": 
      {
          "type": "object",
          "properties": 
          {
            "DEFAULT_PORT": {
              "type" : "integer"     
            },
            "MAX_PORT": {
              "type" : "integer"     
            },
            "MIN_PORT": {
              "type" : "integer"     
            }

          }
        },

        "TEXT_OUTPUT": 
        {
            "type": "object",
            "properties": 
            {
              "CONTROLLER_NAME_MAX_LENGTH": {
              "type": "integer"
              }
            }
        },  



        "RESPONSE_WAITING_TIME" :
        {
            "type" : "number"
        },

        "RETRY_WAITING_TIME" :
        {
            "type" : "number"
        },

        "LOG_FILES" :
          {
            "PATH": {
              "type" : "string"     
            },
            "ROTATION_STYLE": {
              "enum": ["daily","weekly","monthly"]     
            },
            "ROTATION_DEPTH":
            {
              "type": "integer"
            }

          },

        "FTP_SERVER" : 
        {
          "IP_ADDRESS": {
            "type" : "ipv4"
          },
          "LOGIN" : {
            "type" : "string"
          },
          "PASSWORD" : {
            "type" : "string"
          },
          "SERVER_DIRECTORY": {
            "type" : "string"
          },
          "HOST_TEMPORARY_AUTOMATION_FILE" : {
            "type" : "string"
          }
        },


        "CONFIGURATION_PATH": {
          "type" : "array",
          "items": {
              "type": "string"
          }

        },
        
        "CONNECTION_SERVER": {
            "IP_ADDRESS": {
            "type": "ipv4" 
            }
        },


        "TEST": {
          "CONFIGURATION_PATH_SOURCE": {
            "type" : "string"
            },

          "CONFIGURATION_PATH_GEN": {
                  "type": "string" 
              },
            "UDP_SERVER_PORT": {              
                "type" : "integer"     
              },

          "UDP_SERVER_ADDRESS": {
            "type" : "ipv4"

          },
              "CCAN_INT": {
                "type" : "str"     
              }
        },


        "FIRMWARE": {
          "type" : "array",
          "items": 
          {
            "type": "object",
            "properties": 
            {
              "controller": {
              "type": "string"
              },
              "filename": {
                "type": "string"
              }            
            }
          }
        },

        "BOOTLOADER": {
          "type" : "array",
          "items": 
          {
            "type": "object",
            "properties": 
            {
              "controller": {
              "type": "string"
              },
              "filename": {
                "type": "string"
              }            
            }
          }
        }
  }
}

=== ChristophDelfs/CCAN_Integration/CCAN.json
{
  "UDP_SERVER":
  { 
    "DEFAULT_PORT" : 6005, 
    "MIN_PORT"     : 6000,
    "MAX_PORT"     : 6200  
  },
  
  "RESPONSE_WAITING_TIME" : 0.15,
  "RETRY_WAITING_TIME": 1,


  "CONFIGURATION_PATH" : [ "production/gen",           
                            "test/gen" 
                          ],

  "CONNECTION_SERVER" : 
  {
    "IP_ADDRESS" : "192.168.2.14"
  },

  "LOG_FILES"  :
  {

   "PATH" : "production/log",
   "NUMBER_OF_LOG_FILES" : 5,
   "MAX_SIZE_MB" : 10
  },

  "FTP_SERVER" :  
  {
    "IP_ADDRESS" : "192.168.2.49",
    "LOGIN"   :  "ccan",
    "PASSWORD": "ccan",
    "TEMPORARY_AUTOMATION_FILE" : "/tmp/automation.pkl"
  },


  "TEST": 
  {
    "CONFIGURATION_PATH_SOURCE": "test/py/config",      
    "CONFIGURATION_PATH_GEN"    : "test/gen",
    "UDP_SERVER_PORT"           : 6005,
    "UDP_SERVER_ADDRESS"        : "localhost",
    "CCAN_INT"                  : "cli/build/ccan_int"
  },
                      
  "FIRMWARE":  [
    {
        "controller": "NUCLEO_G474RE",
        "filename"  : "boards/mbed_applications/cmake_build/NUCLEO_G474RE_FIRMWARE/release/GCC_ARM/ccan_firmware.hex"
    },
    {
      "controller": "LPC4088_IP",
      "filename" : "boards/lpc4088/build/ccan_firmware_release.hex"
    }      
  ],

  "BOOTLOADER":  [
  {
      "controller": "NUCLEO_G474RE",
      "filename"  : "boards/mbed_applications/cmake_build/NUCLEO_G474RE_UPDATER/release/GCC_ARM/ccan_bootloader_updater.hex"
  },
  {
    "controller": "LPC4088_IP",
    "filename"  : "boards/lpc4088/build/ccan_bootloader_updater_debug.hex"
  }
  
  ],

  "TEXT_OUTPUT": {   
      "CONTROLLER_NAME_MAX_LENGTH" : 30    
  }


}
